services:
  image:
    build: .
    image: spotdl-sd-docker:latest

  download:
    image: spotdl-sd-docker:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./source/source.txt:/source/source.txt:ro
      - ./export:/export
    environment:
      - URLS_FILE_SOURCE
      - OUTPUT_DIRECTORY
    command: ./scripts/download.sh
